version: '3.8'

services:
#  # Eureka Server

  # Spring Cloud Gateway
#  gateway_service:
#    image: geonoo/gateway-service:latest
#    container_name: gateway_service
#    ports:
#      - "8080:8080"

  # User Service
  user_service:
    image: geonoo/user-service:latest
    container_name: user_service
    ports:
      - "8081:8081"

#  # Content Service

  # Group Service
  group_service:
    image: geonoo/group-service:latest
    container_name: group_service
    ports:
      - "8083:8083"

#  # Game Service

#  # Notification Service