name: Build and Deploy MSA
run-name: Running CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 17 설정
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # 3. Docker 로그인
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_HUB_ACCESSKEY }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # 4. 각 서비스별 application.yml 생성 및 Docker 빌드/푸시
      - name: Generate application.yml for User Service
        working-directory: ./user_service
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.USER_SERVICE_APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: Build User Service with Gradle
        working-directory: ./user_service
        run: ./gradlew build

      - name: Build and Push User Service
        working-directory: ./user_service
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/user-service .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-service

      - name: Generate application.yml for Group Service
        working-directory: ./group_service
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.GROUP_SERVICE_APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: Build Group Service with Gradle
        working-directory: ./group_service
        run: ./gradlew build

      - name: Build and Push Group Service
        working-directory: ./group_service
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/group-service .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/group-service

      # 추가 서비스들 반복...

      # 5. Docker 컨테이너 배포 (EC2 또는 서버)
      - name: Upload docker-compose.yml to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > urdego-keypair.pem
          chmod 600 urdego-keypair.pem
          scp -o StrictHostKeyChecking=no -i urdego-keypair.pem docker-compose.yml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/

      - name: Deploy Docker Containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/user-service
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/group-service
            docker compose down
            docker compose up -d
          EOF