name: google-java-format

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "**/*.java --replace --aosp"
          commit-message: "Format : Google Java Format"
